name: serialization
version: 0.10.0
author: Alan Knight <alanknight@google.com>
description: Provide a serialization facility for Dart objects.
homepage: https://github.com/google/serialization.dart
environment:
  sdk: '>=1.0.0 <2.0.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.12.0'
